production:
  <<: *default
  database: errorshare_production
  username: errorshare
  password: <%= ENV['ERRORSHARE_DATABASE_PASSWORD'] %>


default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: errorshare_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: errorshare_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>